const $=(id)=>document.getElementById(id);const fmt=(v)=>Number(v||0).toLocaleString();
async function request(path,options={}){const r=await fetch(`/api/admin/${path}`,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const b=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(b.message||'Request failed');e.status=r.status;throw e}return b}
function showLogin(){ $('login').hidden=false;$('dashboard').hidden=true }
function showDashboard(){ $('login').hidden=true;$('dashboard').hidden=false }
function days(){const d=Number($('days').value);const end=Math.floor(Date.now()/1000);return {start_date:end-d*86400,end_date:end,lite:false,exclude_automated:true,exclude_proxy_backfill:true,exclude_nonhuman_backfill:true}}
function bars(target,vals){const values=(vals||[]).map(Number);const max=Math.max(...values,1);$(target).innerHTML=values.slice(-30).map((v,i)=>`<div class="bar" style="height:${Math.max(3,v/max*190)}px"><span>${i+1}</span></div>`).join('')||'<p class="muted">No activity in this period.</p>'}
function funnel(target,f){$(target).innerHTML=[['Home views',f.view_home],['Download clicks',f.click_download],['Pricing views',f.view_pricing],['Purchases',f.purchase]].map(([l,v])=>`<div><span>${l}</span><strong>${fmt(v)}</strong></div>`).join('')}
function render(data){const o=data.overview||{};const items=[['Sessions',o.sessions],['Visitors',o.visitors],['Page views',o.pageviews],['Downloads',o.downloads],['Orders',o.orders]];$('metrics').innerHTML=items.map(([l,v])=>`<div class="metric"><span>${l}</span><strong>${fmt(v)}</strong></div>`).join('');const f=data.funnel||{};funnel('funnel',f);funnel('funnel-overview',f);const c=data.chart||{};bars('chart',(c.views||c.sessions||[]));bars('chart-traffic',(c.views||c.sessions||[]));const g=data.governance_scorecard||{};if(Number(g.scan_runs||0)>0)$('governance').textContent=`${fmt(g.scan_runs)} scan runs recorded. Identified savings: ${fmt(g.identified_savings)}.`;$('freshness').textContent=`Updated ${new Date().toLocaleString()}`}
async function load(){const e=$('dashboard-error');e.hidden=true;try{render(await request('dashboard',{method:'POST',body:JSON.stringify(days())}))}catch(x){if(x.status===401)return showLogin();e.textContent=x.message;e.hidden=false}}
$('login-form').addEventListener('submit',async(e)=>{e.preventDefault();$('login-error').textContent='';try{await request('session/login',{method:'POST',body:JSON.stringify({username:$('username').value,password:$('password').value})});showDashboard();await load()}catch(x){$('login-error').textContent='Incorrect username or password.'}});$('logout').addEventListener('click',async()=>{await request('session/logout',{method:'POST',body:'{}'});showLogin()});$('refresh').addEventListener('click',load);$('days').addEventListener('change',load);request('session/me').then((x)=>x.authenticated?(showDashboard(),load()):showLogin()).catch(showLogin);
document.querySelectorAll('.tab').forEach((tab)=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach((t)=>t.classList.toggle('active',t===tab));document.querySelectorAll('.tab-panel').forEach((p)=>p.hidden=p.id!==`tab-${tab.dataset.tab}`)}));$('login-form').addEventListener('submit',async(e)=>{e.preventDefault();$('login-error').textContent='';try{await request('session/login',{method:'POST',body:JSON.stringify({username:$('username').value,password:$('password').value})});showDashboard();await load()}catch(x){$('login-error').textContent='Incorrect username or password.'}});$('logout').addEventListener('click',async()=>{await request('session/logout',{method:'POST',body:'{}'});showLogin()});$('refresh').addEventListener('click',load);$('days').addEventListener('change',load);request('session/me').then((x)=>x.authenticated?(showDashboard(),load()):showLogin()).catch(showLogin);
